import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { motion } from 'framer-motion';
import { LineChart as LineChartIcon } from 'lucide-react';

const data = [
  { month: 'Jan', seo: 2400, ppc: 4000, social: 1800, email: 1200 },
  { month: 'Feb', seo: 3200, ppc: 4200, social: 2400, email: 1600 },
  { month: 'Mar', seo: 4100, ppc: 4800, social: 3200, email: 2100 },
  { month: 'Apr', seo: 5400, ppc: 5200, social: 4100, email: 2800 },
  { month: 'May', seo: 7200, ppc: 5800, social: 5200, email: 3400 },
  { month: 'Jun', seo: 9100, ppc: 6400, social: 6800, email: 4200 },
];

const ChannelPerformance = () => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.6 }}
      className="bg-card rounded-2xl border border-border p-6 shadow-lg"
    >
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 bg-gradient-to-r from-indigo-500 to-purple-500 rounded-xl flex items-center justify-center">
          <LineChartIcon className="w-5 h-5 text-white" />
        </div>
        <div>
          <h3 className="font-bold text-foreground">Channel Performance</h3>
          <p className="text-sm text-muted-foreground">Leads generated by marketing channel</p>
        </div>
      </div>
      
      <div className="h-72">
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={data}>
            <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
            <XAxis dataKey="month" stroke="hsl(var(--muted-foreground))" fontSize={12} />
            <YAxis stroke="hsl(var(--muted-foreground))" fontSize={12} />
            <Tooltip
              contentStyle={{
                backgroundColor: 'hsl(var(--card))',
                border: '1px solid hsl(var(--border))',
                borderRadius: '8px',
                color: 'hsl(var(--foreground))',
              }}
            />
            <Legend />
            <Line type="monotone" dataKey="seo" stroke="#3b82f6" strokeWidth={2} dot={{ fill: '#3b82f6', r: 4 }} name="SEO" />
            <Line type="monotone" dataKey="ppc" stroke="#8b5cf6" strokeWidth={2} dot={{ fill: '#8b5cf6', r: 4 }} name="PPC" />
            <Line type="monotone" dataKey="social" stroke="#ec4899" strokeWidth={2} dot={{ fill: '#ec4899', r: 4 }} name="Social" />
            <Line type="monotone" dataKey="email" stroke="#14b8a6" strokeWidth={2} dot={{ fill: '#14b8a6', r: 4 }} name="Email" />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </motion.div>
  );
};

export default ChannelPerformance;
