import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { FileQuestion, Copy, CheckCircle2, Download, Plus, Trash2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const RobotsTxtGeneratorTool = () => {
  const [sitemapUrl, setSitemapUrl] = useState("");
  const [rules, setRules] = useState<{ userAgent: string; disallow: string[] }[]>([
    { userAgent: "*", disallow: [] }
  ]);
  const [commonRules, setCommonRules] = useState({
    blockAdmin: true,
    blockWpAdmin: false,
    blockPrivate: true,
    blockApi: false,
    blockSearch: false,
    allowAll: false
  });
  const [generatedContent, setGeneratedContent] = useState("");
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const predefinedPaths = [
    { id: "blockAdmin", label: "Block /admin/", path: "/admin/" },
    { id: "blockWpAdmin", label: "Block /wp-admin/", path: "/wp-admin/" },
    { id: "blockPrivate", label: "Block /private/", path: "/private/" },
    { id: "blockApi", label: "Block /api/", path: "/api/" },
    { id: "blockSearch", label: "Block /search", path: "/search" },
  ];

  const addRule = () => {
    setRules([...rules, { userAgent: "*", disallow: [] }]);
  };

  const removeRule = (index: number) => {
    if (rules.length > 1) {
      setRules(rules.filter((_, i) => i !== index));
    }
  };

  const updateRuleUserAgent = (index: number, value: string) => {
    const newRules = [...rules];
    newRules[index].userAgent = value;
    setRules(newRules);
  };

  const addDisallowPath = (index: number, path: string) => {
    if (!path.trim()) return;
    const newRules = [...rules];
    if (!newRules[index].disallow.includes(path)) {
      newRules[index].disallow.push(path);
      setRules(newRules);
    }
  };

  const removeDisallowPath = (ruleIndex: number, pathIndex: number) => {
    const newRules = [...rules];
    newRules[ruleIndex].disallow.splice(pathIndex, 1);
    setRules(newRules);
  };

  const generateRobotsTxt = () => {
    let content = "# Robots.txt generated by Digital Bull Free Tools\n";
    content += "# https://dibull.com/free-tools/robots-txt-generator\n\n";

    if (commonRules.allowAll) {
      content += "User-agent: *\n";
      content += "Allow: /\n\n";
    } else {
      rules.forEach((rule) => {
        content += `User-agent: ${rule.userAgent}\n`;
        
        // Add common rules
        if (commonRules.blockAdmin) content += "Disallow: /admin/\n";
        if (commonRules.blockWpAdmin) content += "Disallow: /wp-admin/\n";
        if (commonRules.blockPrivate) content += "Disallow: /private/\n";
        if (commonRules.blockApi) content += "Disallow: /api/\n";
        if (commonRules.blockSearch) content += "Disallow: /search\n";
        
        // Add custom disallow paths
        rule.disallow.forEach((path) => {
          content += `Disallow: ${path}\n`;
        });
        
        content += "\n";
      });
    }

    if (sitemapUrl.trim()) {
      content += `Sitemap: ${sitemapUrl}\n`;
    }

    setGeneratedContent(content);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedContent);
    setCopied(true);
    toast({
      title: "Copied!",
      description: "Robots.txt content copied to clipboard.",
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([generatedContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({
      title: "Downloaded!",
      description: "robots.txt file downloaded successfully.",
    });
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileQuestion className="w-5 h-5 text-emerald-500" />
            Robots.txt Generator
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Sitemap URL */}
          <div>
            <label className="block text-sm font-medium mb-2">Sitemap URL (optional)</label>
            <Input
              placeholder="https://example.com/sitemap.xml"
              value={sitemapUrl}
              onChange={(e) => setSitemapUrl(e.target.value)}
            />
          </div>

          {/* Common Rules */}
          <div>
            <label className="block text-sm font-medium mb-3">Quick Options</label>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="allowAll"
                  checked={commonRules.allowAll}
                  onCheckedChange={(checked) => 
                    setCommonRules({ ...commonRules, allowAll: checked as boolean })
                  }
                />
                <label htmlFor="allowAll" className="text-sm cursor-pointer">
                  Allow All Crawlers
                </label>
              </div>
              {predefinedPaths.map((item) => (
                <div key={item.id} className="flex items-center space-x-2">
                  <Checkbox
                    id={item.id}
                    checked={commonRules[item.id as keyof typeof commonRules] as boolean}
                    onCheckedChange={(checked) => 
                      setCommonRules({ ...commonRules, [item.id]: checked as boolean })
                    }
                    disabled={commonRules.allowAll}
                  />
                  <label htmlFor={item.id} className="text-sm cursor-pointer">
                    {item.label}
                  </label>
                </div>
              ))}
            </div>
          </div>

          {/* Custom Rules */}
          {!commonRules.allowAll && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <label className="block text-sm font-medium">Custom Rules</label>
                <Button variant="outline" size="sm" onClick={addRule}>
                  <Plus className="w-4 h-4 mr-1" />
                  Add Rule
                </Button>
              </div>

              {rules.map((rule, ruleIndex) => (
                <div key={ruleIndex} className="p-4 border border-border rounded-lg space-y-3">
                  <div className="flex items-center gap-2">
                    <Input
                      placeholder="User-agent (e.g., * or Googlebot)"
                      value={rule.userAgent}
                      onChange={(e) => updateRuleUserAgent(ruleIndex, e.target.value)}
                      className="flex-1"
                    />
                    {rules.length > 1 && (
                      <Button variant="ghost" size="icon" onClick={() => removeRule(ruleIndex)}>
                        <Trash2 className="w-4 h-4 text-destructive" />
                      </Button>
                    )}
                  </div>

                  <div className="flex gap-2">
                    <Input
                      placeholder="Add disallow path (e.g., /private/)"
                      onKeyDown={(e) => {
                        if (e.key === 'Enter') {
                          addDisallowPath(ruleIndex, (e.target as HTMLInputElement).value);
                          (e.target as HTMLInputElement).value = '';
                        }
                      }}
                    />
                  </div>

                  {rule.disallow.length > 0 && (
                    <div className="flex flex-wrap gap-2">
                      {rule.disallow.map((path, pathIndex) => (
                        <span
                          key={pathIndex}
                          className="inline-flex items-center gap-1 px-2 py-1 bg-muted rounded text-sm"
                        >
                          {path}
                          <button
                            onClick={() => removeDisallowPath(ruleIndex, pathIndex)}
                            className="text-muted-foreground hover:text-destructive"
                          >
                            ×
                          </button>
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}

          <Button onClick={generateRobotsTxt} className="w-full">
            <FileQuestion className="w-4 h-4 mr-2" />
            Generate Robots.txt
          </Button>
        </CardContent>
      </Card>

      {generatedContent && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Generated Robots.txt</CardTitle>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" onClick={copyToClipboard}>
                  {copied ? (
                    <>
                      <CheckCircle2 className="w-4 h-4 mr-2 text-green-500" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4 mr-2" />
                      Copy
                    </>
                  )}
                </Button>
                <Button variant="outline" size="sm" onClick={downloadFile}>
                  <Download className="w-4 h-4 mr-2" />
                  Download
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <Textarea
              value={generatedContent}
              readOnly
              className="min-h-[200px] font-mono text-sm"
            />
          </CardContent>
        </Card>
      )}
    </div>
  );
};

export default RobotsTxtGeneratorTool;
