import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import AdminLayout from "@/components/admin/AdminLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { MessageCircle, Download, Search, Clock, User, Bot, ChevronRight, FileText, RefreshCw } from "lucide-react";
import { format } from "date-fns";

type ChatMsg = {
  id: string;
  session_id: string;
  role: string;
  content: string;
  created_at: string;
};

type SessionSummary = {
  session_id: string;
  message_count: number;
  first_message: string;
  last_message: string;
  preview: string;
};

const AdminChatConversations = () => {
  const [sessions, setSessions] = useState<SessionSummary[]>([]);
  const [selectedSession, setSelectedSession] = useState<string | null>(null);
  const [sessionMessages, setSessionMessages] = useState<ChatMsg[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);

  const fetchSessions = async () => {
    setLoading(true);
    const { data } = await supabase
      .from("chat_messages")
      .select("*")
      .order("created_at", { ascending: true });

    if (!data) { setLoading(false); return; }

    // Group by session_id
    const grouped: Record<string, ChatMsg[]> = {};
    for (const msg of data) {
      if (!grouped[msg.session_id]) grouped[msg.session_id] = [];
      grouped[msg.session_id].push(msg);
    }

    const summaries: SessionSummary[] = Object.entries(grouped)
      .map(([sid, msgs]) => {
        const userMsgs = msgs.filter(m => m.role === "user");
        return {
          session_id: sid,
          message_count: msgs.length,
          first_message: msgs[0].created_at,
          last_message: msgs[msgs.length - 1].created_at,
          preview: userMsgs[0]?.content || "No user message",
        };
      })
      .sort((a, b) => new Date(b.last_message).getTime() - new Date(a.last_message).getTime());

    setSessions(summaries);
    setLoading(false);
  };

  useEffect(() => { fetchSessions(); }, []);

  const loadSession = async (sid: string) => {
    setSelectedSession(sid);
    const { data } = await supabase
      .from("chat_messages")
      .select("*")
      .eq("session_id", sid)
      .order("created_at", { ascending: true });
    setSessionMessages(data || []);
  };

  const downloadAsDoc = (sid: string) => {
    const msgs = sessionMessages;
    if (!msgs.length) return;

    let docContent = `<html><head><meta charset="utf-8"><title>Chat Conversation - ${sid}</title>
    <style>
      body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #333; }
      h1 { color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 10px; font-size: 22px; }
      .meta { color: #666; font-size: 13px; margin-bottom: 30px; }
      .msg { margin: 16px 0; padding: 12px 16px; border-radius: 12px; }
      .user { background: #eff6ff; border-left: 4px solid #3b82f6; }
      .assistant { background: #f0fdf4; border-left: 4px solid #22c55e; }
      .role { font-weight: bold; font-size: 12px; text-transform: uppercase; margin-bottom: 4px; }
      .role.user-role { color: #1d4ed8; }
      .role.bot-role { color: #15803d; }
      .time { color: #999; font-size: 11px; float: right; }
      .content { font-size: 14px; line-height: 1.6; white-space: pre-wrap; }
      .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #999; font-size: 12px; text-align: center; }
    </style></head><body>`;

    docContent += `<h1>💬 DiBull Chat Conversation</h1>`;
    docContent += `<div class="meta">
      <strong>Session ID:</strong> ${sid}<br>
      <strong>Date:</strong> ${format(new Date(msgs[0].created_at), "PPpp")}<br>
      <strong>Total Messages:</strong> ${msgs.length}
    </div>`;

    for (const msg of msgs) {
      const roleClass = msg.role === "user" ? "user" : "assistant";
      const roleLabel = msg.role === "user" ? "👤 Visitor" : "🤖 DiBull Assistant";
      const roleLabelClass = msg.role === "user" ? "user-role" : "bot-role";
      docContent += `<div class="msg ${roleClass}">
        <span class="role ${roleLabelClass}">${roleLabel}</span>
        <span class="time">${format(new Date(msg.created_at), "hh:mm a")}</span>
        <div class="content">${msg.content.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
      </div>`;
    }

    docContent += `<div class="footer">Generated by DiBull Technology Admin Panel • ${format(new Date(), "PPpp")}</div>`;
    docContent += `</body></html>`;

    const blob = new Blob([docContent], { type: "application/msword" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `DiBull-Chat-${sid.slice(0, 12)}.doc`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const filteredSessions = sessions.filter(s =>
    s.session_id.toLowerCase().includes(search.toLowerCase()) ||
    s.preview.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <AdminLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2">
              <MessageCircle className="w-6 h-6 text-primary" />
              Chat Conversations
            </h1>
            <p className="text-muted-foreground text-sm mt-1">
              View all DiBull Assistant conversations & download transcripts
            </p>
          </div>
          <Button variant="outline" size="sm" onClick={fetchSessions}>
            <RefreshCw className="w-4 h-4 mr-2" /> Refresh
          </Button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6" style={{ minHeight: "70vh" }}>
          {/* Sessions List */}
          <Card className="lg:col-span-1">
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                Sessions
                <Badge variant="secondary" className="ml-auto">{sessions.length}</Badge>
              </CardTitle>
              <div className="relative mt-2">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <Input
                  placeholder="Search conversations..."
                  className="pl-9 text-sm"
                  value={search}
                  onChange={e => setSearch(e.target.value)}
                />
              </div>
            </CardHeader>
            <CardContent className="p-0">
              <ScrollArea className="h-[60vh]">
                {loading ? (
                  <div className="p-6 text-center text-muted-foreground text-sm">Loading...</div>
                ) : filteredSessions.length === 0 ? (
                  <div className="p-6 text-center text-muted-foreground text-sm">No conversations yet</div>
                ) : (
                  filteredSessions.map(s => (
                    <button
                      key={s.session_id}
                      onClick={() => loadSession(s.session_id)}
                      className={`w-full text-left px-4 py-3 border-b border-border hover:bg-muted/50 transition-colors ${
                        selectedSession === s.session_id ? "bg-primary/5 border-l-2 border-l-primary" : ""
                      }`}
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs font-mono text-muted-foreground">
                          {s.session_id.slice(5, 20)}...
                        </span>
                        <ChevronRight className="w-3.5 h-3.5 text-muted-foreground" />
                      </div>
                      <p className="text-sm font-medium truncate">{s.preview}</p>
                      <div className="flex items-center gap-3 mt-1 text-xs text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <Clock className="w-3 h-3" />
                          {format(new Date(s.last_message), "MMM d, hh:mm a")}
                        </span>
                        <span>{s.message_count} msgs</span>
                      </div>
                    </button>
                  ))
                )}
              </ScrollArea>
            </CardContent>
          </Card>

          {/* Conversation Detail */}
          <Card className="lg:col-span-2">
            <CardHeader className="pb-3 flex-row items-center justify-between">
              <CardTitle className="text-base">
                {selectedSession ? "Conversation" : "Select a conversation"}
              </CardTitle>
              {selectedSession && sessionMessages.length > 0 && (
                <Button size="sm" variant="outline" onClick={() => downloadAsDoc(selectedSession)}>
                  <Download className="w-4 h-4 mr-2" />
                  Download .doc
                </Button>
              )}
            </CardHeader>
            <CardContent className="p-0">
              <ScrollArea className="h-[60vh]">
                {!selectedSession ? (
                  <div className="flex flex-col items-center justify-center h-[50vh] text-muted-foreground">
                    <FileText className="w-12 h-12 mb-3 opacity-30" />
                    <p className="text-sm">Select a session from the left to view the conversation</p>
                  </div>
                ) : sessionMessages.length === 0 ? (
                  <div className="p-6 text-center text-muted-foreground text-sm">Loading messages...</div>
                ) : (
                  <div className="p-4 space-y-3">
                    {sessionMessages.map(msg => (
                      <div key={msg.id} className={`flex gap-3 ${msg.role === "user" ? "flex-row-reverse" : ""}`}>
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${
                          msg.role === "user"
                            ? "bg-blue-500/10 text-blue-600"
                            : "bg-green-500/10 text-green-600"
                        }`}>
                          {msg.role === "user" ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
                        </div>
                        <div className={`max-w-[75%] rounded-xl px-4 py-2.5 text-sm ${
                          msg.role === "user"
                            ? "bg-blue-500/10 text-foreground"
                            : "bg-muted text-foreground"
                        }`}>
                          <p className="whitespace-pre-wrap">{msg.content}</p>
                          <p className="text-[10px] text-muted-foreground mt-1">
                            {format(new Date(msg.created_at), "hh:mm a")}
                          </p>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </ScrollArea>
            </CardContent>
          </Card>
        </div>
      </div>
    </AdminLayout>
  );
};

export default AdminChatConversations;
